services:
  audiobookbay-automated:
    image: ${IMAGE_NAME:-ghcr.io/jamesry96/audiobookbay-automated:latest}
    ports:
      - "5078:5078"
    container_name: audiobookbay-automated
    env_file:
      - ${APP_ENV_FILE:-.env}
